// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://krlltvtdfwnaxrdmknhq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtybGx0dnRkZnduYXhyZG1rbmhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk3MzI2MTksImV4cCI6MjA4NTMwODYxOX0.mM-_h38psRL1aYl7v8bOXy18eXYZ1uaX74BLcmI2OV4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});